module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    "welcome",
    {
      type: "category",
      label: "Introduction",
      items: [
        {
          type: "autogenerated",
          dirName: "01-introduction",
        },
      ],
    },
    {
      type: "category",
      label: "The basics",
      items: [
        {
          type: "autogenerated",
          dirName: "02-the-basics",
        },
      ],
    },
    {
      type: "category",
      label: "Setting you up for the dev life",
      items: [
        {
          type: "autogenerated",
          dirName: "03-set-up",
        },
      ],
    },
  ],
};
